orders/urls.py
from django.urls import path
from .views import OrderSubmit, OrdersList

urlpatterns = [
    path('order/<int:inventoryid>/', OrderSubmit, name='submit_order'),
    path('orders_list/<int:user_id>/', OrdersList, name='order_list'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('product.urls')),
    path('', include('orders.urls')),
    path('adminpanel/', include('adminpanel.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from product.models import Product, Inventory
from django.contrib.auth.models import User

class Order(models.Model):
    STATUS = (
        ('pending', 'در انتظار بازبینی'),
        ('deliver', 'آماده ارسال'),
        ('Post', 'ارسال شده'),
        ('cancel', 'لغو شده'),
    )
    user = models.ForeignKey(User, related_name='O_user',on_delete=models.CASCADE ,verbose_name='کاربر')
    product = models.ForeignKey(Product, related_name='O_product',on_delete=models.CASCADE ,verbose_name='محصول')
    price = models.PositiveBigIntegerField(verbose_name='قیمت کالا')
    inventory = models.ForeignKey(Inventory, related_name='O_inventory', on_delete=models.CASCADE, verbose_name='انبار')
    quantity = models.PositiveIntegerField(verbose_name='تعداد')
    status = models.CharField(max_length=15, choices=STATUS, verbose_name='وضعیت سفارش')
    create = models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت سفارش')

    def __str__(self):
        return f'{self.id}'

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش ها'

product/models.py
from django.db import models
from django.utils.safestring import mark_safe

class City(models.Model):
    name = models.CharField(max_length=120, unique=True, verbose_name='نام شهر')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'شهر'
        verbose_name_plural = 'شهر ها'

class Product(models.Model):
    STATUS = (
        ('kg', 'کیلوگرم'),
        ('pack', 'بسته'),
        ('num', 'عدد'),
    )
    name = models.CharField(max_length=120, unique=True, verbose_name='نام')
    price = models.PositiveBigIntegerField(verbose_name='قیمت')
    quantity = models.PositiveIntegerField(verbose_name='موجودی')
    unit = models.CharField(max_length=20, choices=STATUS, verbose_name='واحد')
    image = models.ImageField(upload_to='product/%Y/%B/%d/', verbose_name='تصویر')

    def __str__(self):
        return self.name

    def price_decimal(self):
        return f'{self.price:,}'
    price_decimal.short_description = 'قیمت'

    def product_image(self):
        return mark_safe('<img src="{}" width="80" style="border-radius:50%;" />'.format(self.image.url))

    product_image.short_description = 'تصویر'
    product_image.allow_tags = True

    class Meta:
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'

class Inventory(models.Model):
    name = models.CharField(max_length=120, unique=True, verbose_name='نام انبار')
    city = models.ForeignKey(City, related_name='inv_city',on_delete=models.CASCADE ,verbose_name='شهر')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'انبار'
        verbose_name_plural = 'انبار ها'

class InventoryProduct(models.Model):
    product = models.ForeignKey(Product, related_name='inp_product',on_delete=models.CASCADE ,verbose_name='محصول')
    inventory = models.ForeignKey(Inventory, related_name='inp_inventory', on_delete=models.CASCADE, verbose_name='انبار')
    quantity = models.PositiveIntegerField(verbose_name='موجودی کالا')

    def __str__(self):
        return f'{self.id}'

    class Meta:
        verbose_name = 'موجودی انبار'
        verbose_name_plural = 'موجودی انبار ها'
        unique_together = [("product", "inventory")]

orders/forms.py
from django import forms
from .models import Order
from product.models import *

class OrderCheckForm(forms.ModelForm):

    class Meta:
        model = Order
        exclude = []
    def __init__(self, *args, **kwargs):
        global change_order
        change_order = kwargs.get('instance')
        super(OrderCheckForm, self).__init__(*args, **kwargs)

    def clean_product(self):
        user = self.cleaned_data.get('user')
        product = self.cleaned_data.get('product')
        product = Product.objects.get(name__exact=product)
        product_city = product.inp_product.filter(inventory__city__name__exact=user.usercity)
        if not product_city:
            raise forms.ValidationError(f'این محصول در شهر کاربر وجود ندارد')

        return product

    def clean_inventory(self):
        user = self.cleaned_data.get('user')
        product = self.cleaned_data.get('product')
        inventory = self.cleaned_data.get('inventory')
        if product is not None:
            inventoryproduct = InventoryProduct.objects.filter(product__name__exact=product, inventory__name__exact=inventory)
            inventoryuser = Inventory.objects.filter(name__exact=inventory,city__name__exact=user.usercity)
            if not inventoryproduct:
                raise forms.ValidationError(f'این محصول در این انبار وجود ندارد')

            elif not inventoryuser:
                raise forms.ValidationError(f'این انبار مربوط به شهر این کاربر نیست')

        return inventory


    def clean_quantity(self):
        product = self.cleaned_data.get('product')
        quantity = self.cleaned_data.get('quantity')
        inventory = self.cleaned_data.get('inventory')
        last_quantity = None
        if product is not None and inventory is not None:
            product = Product.objects.filter(name__exact=product).first()
            if change_order is None:
                correct_quantity = quantity
            elif change_order is not None:
                order = product.O_product.get(id=change_order.id)
                last_quantity = order.quantity
                correct_quantity = last_quantity - quantity

            product_quantity = product.inp_product.filter(quantity__gte=correct_quantity, inventory=inventory)
            print(product_quantity)
            if not product_quantity:
                raise forms.ValidationError(f'مقدار ثبت شده بیش از موجودی است')
            else:
                used_quantity = quantity if change_order is None else (quantity - order.quantity) if last_quantity < quantity else quantity
                inventoryproduct = InventoryProduct.objects.filter(inventory=inventory, product=product).first()
                if last_quantity is None or last_quantity < quantity:
                    product.quantity -= used_quantity
                    inventoryproduct.quantity -= used_quantity
                else:
                    product.quantity += last_quantity - used_quantity
                    inventoryproduct.quantity += last_quantity - used_quantity
            product.save()
            inventoryproduct.save()

        return quantity

    def clean_status(self):
        status = self.cleaned_data.get('status')
        quantity = self.cleaned_data.get('quantity')
        product = self.cleaned_data.get('product')
        inventory = self.cleaned_data.get('inventory')
        last_status = None
        if change_order is not None:
            order = product.O_product.get(id=change_order.id)
            last_status = order.status
        if inventory and product and quantity and last_status != 'cancel':
            product = Product.objects.get(name__exact=product)
            inventoryproduct = InventoryProduct.objects.get(inventory=inventory, product=product)
            if status=='cancel':
                product.quantity += quantity
                inventoryproduct.quantity += quantity
            product.save()
            inventoryproduct.save()
        elif last_status == 'cancel':
            raise forms.ValidationError(f'شما نمیتوانید تنظیمات سفارشات لغو شده را تغییر دهید')

        return status


class OrderForm(forms.Form):
    quantity_need = forms.IntegerField(min_value=1,
        widget=forms.NumberInput(attrs={"class": "form-control", "placeholder": "مقدار مورد نظر خود را وارد کنید"}))

orders/views.py
from django.shortcuts import render, redirect
from product.models import Product, InventoryProduct
from .models import Order
from django.contrib.auth.decorators import login_required
from .forms import OrderForm
from django.contrib import messages


@login_required(login_url='/login')
def OrderSubmit(request,inventoryid):
    inventory = InventoryProduct.objects.get(id__exact=inventoryid)
    order_form = OrderForm(request.POST or None)
    if request.method == 'POST':
        if order_form.is_valid():
            quantity_need = order_form.cleaned_data.get("quantity_need")
            if quantity_need > inventory.quantity:
                order_form.add_error('quantity_need', 'درخواست شما بیشتر از حد مجاز است')
            else:
                Order.objects.create(user=request.user, product=inventory.product, price=inventory.product.price ,inventory=inventory.inventory, quantity=quantity_need, status='pending')
                inventory.quantity -= quantity_need
                inventory.save()
                product = Product.objects.get(id=inventory.product.id)
                product.quantity -= quantity_need
                product.save()
                messages.success(request, 'سفارش شما ثبت شد و در حال پردازش میباشد.')
                return redirect('/')
    context ={
        "inventory" : inventory,
        "order_form": order_form
    }
    return render(request, 'orders/order.html', context)

@login_required(login_url='/login')
def OrdersList(request,user_id):
    orders = Order.objects.filter(user_id__exact=user_id)
    context ={
        "orders" : orders,
    }
    return render(request, 'orders/orders_list.html', context)

orders/templates/orders/order.html
{% extends 'base.html' %}
{% load static %}
{% block bodystyle %}
    <body style="background-image: url('{% static "images/back_shop.jpg" %}'); height: 100%; background-position: center; background-size: cover;background-repeat: no-repeat; background-attachment: fixed;">
{% endblock %}
{% block addjs %}
<script>
    function clicked() {
    return confirm('آیا از سفارش خود اطمینان دارید ؟');
}
</script>
{% endblock %}
{% block content %}
<div class="container">
      <div class="card text-right col-md-12">
        <img style="width: 250px; height: 350px; margin: auto" src="{{ inventory.product.image.url }}" alt="Card image cap">
        <div class="card-body">
          <h5 class="card-title">{{ inventory.product.name }}</h5>
          <p class="card-text">قیمت هر {{ inventory.product.get_unit_display }} : {{ inventory.product.price_decimal }} تومان</p>
          <p class="card-text">موجودی : {{ inventory.quantity }} {{ inventory.product.get_unit_display }}</p>
        </div>
        <div class="card-footer">
          <form method="POST" action="">
                {% csrf_token %}
                {% for error in order_form.quantity_need.errors %}
                    <span style="color: #bd4147">{{ error }}</span><br>
                {% endfor %}
                <div class="form-group">
                    <label for="your_quantity"><i class="zmdi zmdi-card"></i></label>
                    {{ order_form.quantity_need }}
                </div>
                <div class="form-group form-button">
                    <input type="submit" onclick="return clicked();"  name="order_form" id="order_form" class="btn btn-success btn-block mt-3" value="ثبت سفارش">
                </div>
            </form>
        </div>
      </div>
</div>

{% endblock %}

orders/templates/orders/orders_list.html
{% extends 'base.html' %}
{% load static %}
{% load mytags %}
{% load jalali_tags %}
{% block bodystyle %}
    <body style="background-image: url('{% static "images/back_shop.jpg" %}'); height: 100%; background-position: center; background-size: cover;background-repeat: no-repeat; background-attachment: fixed;">
{% endblock %}
{% block content %}
<div class="container">
<table class="table text-center">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ردیف</th>
      <th scope="col">کالا</th>
      <th scope="col">مقدار سفارش</th>
      <th scope="col">قیمت واحد</th>
      <th scope="col">قیمت کل فاکتور</th>
      <th scope="col">تاریخ ثبت</th>
      <th scope="col">وضعیت سفارش</th>
    </tr>
  </thead>
<tbody style="background-color: #ffffff">
    {% for order in orders %}
        <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.product }}</td>
            <td>{{ order.quantity }}</td>
            <td>{% decimal_price order.price %}</td>
            <td>{% multiply order.price order.quantity %}</td>
            <td>{{ order.create|to_jalali:'%Y/%m/%d _ %H:%M:%S' }}</td>

            {% if order.status == 'pending' %}
                <td><button type="button" class="btn btn-secondary btn-sm">{{ order.get_status_display }}</button></td>
            {% elif order.status == 'deliver' %}
                <td><button type="button" class="btn btn-info btn-sm">{{ order.get_status_display }}</button></td>
            {% elif order.status == 'Post' %}
                <td><button type="button" class="btn btn-success btn-sm">{{ order.get_status_display }}</button></td>
            {% else %}
                <td><button type="button" class="btn btn-danger btn-sm">{{ order.get_status_display }}</button></td>
            {% endif %}
        </tr>
    {% endfor %}
</tbody>
</table>
</div>

{% endblock %}